/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "MainWindow.h"


//==============================================================================
class arteApplication  : public JUCEApplication
{
public:
    //==============================================================================
    arteApplication() {}

    ~arteApplication() {}

    //==============================================================================
    void initialise (const String& commandLine)
    {
        mainWindow = new MainWindow();
        mainWindow->setUsingNativeTitleBar (true);
    }

    void shutdown()
    {
        mainWindow = 0;
    }

    //==============================================================================
    void systemRequestedQuit()
    {quit();}

    //==============================================================================
    const String getApplicationName() { return "arte";}
    const String getApplicationVersion() {return ProjectInfo::versionString;}
    bool moreThanOneInstanceAllowed() {return true;}
    void anotherInstanceStarted (const String& commandLine)
    {}

private:
    ScopedPointer <MainWindow> mainWindow;
};

//==============================================================================
// This macro generates the main() routine that starts the app.
START_JUCE_APPLICATION(arteApplication)
