/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic outline for a simple desktop window.

  ==============================================================================
*/

#include "MainWindow.h"
#include <stdio.h>


//==============================================================================
MainWindow::MainWindow()
    : DocumentWindow (JUCEApplication::getInstance()->getApplicationName(),
                      Colours::darkgrey,
                      DocumentWindow::allButtons)
{
    centreWithSize (500, 400);
    setResizable (true, false);
    //setResizeLimits(500, 400, 10000, 10000);

    // Create ProcessorGraph and AudioComponent, and connect them.
    // Callbacks will be set by the play button in the control panel
    processorGraph = new ProcessorGraph();
    audioComponent = new AudioComponent();
    audioComponent->connectToProcessorGraph(processorGraph);
    
    setContentComponent (new UIComponent(processorGraph, audioComponent), true, true);

    processorGraph->setUIComponent((UIComponent*) getContentComponent());

    setVisible (true);

  // // uncomment next two lines to load saved state on startup:
    //File file = File("./savedState.xml");
    //processorGraph->loadState(file);

}

MainWindow::~MainWindow()
{

  audioComponent->disconnectProcessorGraph();

   deleteAndZero(processorGraph);
   deleteAndZero(audioComponent);

   setContentComponent (0);

}

void MainWindow::closeButtonPressed()
{ 
    if (audioComponent->callbacksAreActive()) {
      audioComponent->endCallbacks();
      processorGraph->disableSourceNodes();
    }

    // // uncomment next two lines to save state on quit:
    //File file = File("./savedState.xml");
    //processorGraph->saveState(file);

    JUCEApplication::getInstance()->systemRequestedQuit();

}
