/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic outline for a simple desktop window.

  ==============================================================================
*/

#include "MainWindow.h"
#include <stdio.h>


//==============================================================================
MainWindow::MainWindow()
    : DocumentWindow (JUCEApplication::getInstance()->getApplicationName(),
                      Colours::darkgrey,
                      DocumentWindow::allButtons)
{
    centreWithSize (500, 400);
    setResizable (true, true);
    //setResizeLimits(500, 400, 1000, 800);

    // create ProcessorGraph and AudioComponent, and connect them.
    // callbacks will be set by the play button in the control panel
    processorGraph = new ProcessorGraph(16);
    audioComponent = new AudioComponent();
    audioComponent->connectToProcessorGraph(processorGraph);
    
    std::cout << "Window width = " << getWidth() << std::endl;
    std::cout << "Window height = " << getHeight() << std::endl;

    setContentComponent (new UIComponent(processorGraph, audioComponent), true, true);

    setVisible (true);

}

MainWindow::~MainWindow()
{
  setContentComponent (0);

  audioComponent->disconnectProcessorGraph();

   deleteAndZero(processorGraph);
   deleteAndZero(audioComponent);

}

void MainWindow::closeButtonPressed()
{
    JUCEApplication::getInstance()->systemRequestedQuit();
}
