// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracker_pb.proto

#ifndef PROTOBUF_tracker_5fpb_2eproto__INCLUDED
#define PROTOBUF_tracker_5fpb_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_tracker_5fpb_2eproto();
void protobuf_AssignDesc_tracker_5fpb_2eproto();
void protobuf_ShutdownFile_tracker_5fpb_2eproto();

class ScaleShift;
class Affine2D;
class CameraOpt;
class CameraGroup;
class Led;
class TrackerOpt;

enum CameraGroup_CombineStyle {
  CameraGroup_CombineStyle_NONE = 1,
  CameraGroup_CombineStyle_PANOSTITCH = 2,
  CameraGroup_CombineStyle_FULL3D = 3
};
bool CameraGroup_CombineStyle_IsValid(int value);
const CameraGroup_CombineStyle CameraGroup_CombineStyle_CombineStyle_MIN = CameraGroup_CombineStyle_NONE;
const CameraGroup_CombineStyle CameraGroup_CombineStyle_CombineStyle_MAX = CameraGroup_CombineStyle_FULL3D;
const int CameraGroup_CombineStyle_CombineStyle_ARRAYSIZE = CameraGroup_CombineStyle_CombineStyle_MAX + 1;

const ::google::protobuf::EnumDescriptor* CameraGroup_CombineStyle_descriptor();
inline const ::std::string& CameraGroup_CombineStyle_Name(CameraGroup_CombineStyle value) {
  return ::google::protobuf::internal::NameOfEnum(
    CameraGroup_CombineStyle_descriptor(), value);
}
inline bool CameraGroup_CombineStyle_Parse(
    const ::std::string& name, CameraGroup_CombineStyle* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CameraGroup_CombineStyle>(
    CameraGroup_CombineStyle_descriptor(), name, value);
}
// ===================================================================

class ScaleShift : public ::google::protobuf::Message {
 public:
  ScaleShift();
  virtual ~ScaleShift();
  
  ScaleShift(const ScaleShift& from);
  
  inline ScaleShift& operator=(const ScaleShift& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ScaleShift& default_instance();
  
  void Swap(ScaleShift* other);
  
  // implements Message ----------------------------------------------
  
  ScaleShift* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ScaleShift& from);
  void MergeFrom(const ScaleShift& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional float x_scale = 1;
  inline bool has_x_scale() const;
  inline void clear_x_scale();
  static const int kXScaleFieldNumber = 1;
  inline float x_scale() const;
  inline void set_x_scale(float value);
  
  // optional float x_shift = 2;
  inline bool has_x_shift() const;
  inline void clear_x_shift();
  static const int kXShiftFieldNumber = 2;
  inline float x_shift() const;
  inline void set_x_shift(float value);
  
  // optional float y_scale = 3;
  inline bool has_y_scale() const;
  inline void clear_y_scale();
  static const int kYScaleFieldNumber = 3;
  inline float y_scale() const;
  inline void set_y_scale(float value);
  
  // optional float y_shift = 4;
  inline bool has_y_shift() const;
  inline void clear_y_shift();
  static const int kYShiftFieldNumber = 4;
  inline float y_shift() const;
  inline void set_y_shift(float value);
  
  // @@protoc_insertion_point(class_scope:ScaleShift)
 private:
  inline void set_has_x_scale();
  inline void clear_has_x_scale();
  inline void set_has_x_shift();
  inline void clear_has_x_shift();
  inline void set_has_y_scale();
  inline void clear_has_y_scale();
  inline void set_has_y_shift();
  inline void clear_has_y_shift();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  float x_scale_;
  float x_shift_;
  float y_scale_;
  float y_shift_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_tracker_5fpb_2eproto();
  friend void protobuf_AssignDesc_tracker_5fpb_2eproto();
  friend void protobuf_ShutdownFile_tracker_5fpb_2eproto();
  
  void InitAsDefaultInstance();
  static ScaleShift* default_instance_;
};
// -------------------------------------------------------------------

class Affine2D : public ::google::protobuf::Message {
 public:
  Affine2D();
  virtual ~Affine2D();
  
  Affine2D(const Affine2D& from);
  
  inline Affine2D& operator=(const Affine2D& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Affine2D& default_instance();
  
  void Swap(Affine2D* other);
  
  // implements Message ----------------------------------------------
  
  Affine2D* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Affine2D& from);
  void MergeFrom(const Affine2D& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated float coef = 1;
  inline int coef_size() const;
  inline void clear_coef();
  static const int kCoefFieldNumber = 1;
  inline float coef(int index) const;
  inline void set_coef(int index, float value);
  inline void add_coef(float value);
  inline const ::google::protobuf::RepeatedField< float >&
      coef() const;
  inline ::google::protobuf::RepeatedField< float >*
      mutable_coef();
  
  // @@protoc_insertion_point(class_scope:Affine2D)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedField< float > coef_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_tracker_5fpb_2eproto();
  friend void protobuf_AssignDesc_tracker_5fpb_2eproto();
  friend void protobuf_ShutdownFile_tracker_5fpb_2eproto();
  
  void InitAsDefaultInstance();
  static Affine2D* default_instance_;
};
// -------------------------------------------------------------------

class CameraOpt : public ::google::protobuf::Message {
 public:
  CameraOpt();
  virtual ~CameraOpt();
  
  CameraOpt(const CameraOpt& from);
  
  inline CameraOpt& operator=(const CameraOpt& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CameraOpt& default_instance();
  
  void Swap(CameraOpt* other);
  
  // implements Message ----------------------------------------------
  
  CameraOpt* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CameraOpt& from);
  void MergeFrom(const CameraOpt& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // optional string dev_or_file_name = 2;
  inline bool has_dev_or_file_name() const;
  inline void clear_dev_or_file_name();
  static const int kDevOrFileNameFieldNumber = 2;
  inline const ::std::string& dev_or_file_name() const;
  inline void set_dev_or_file_name(const ::std::string& value);
  inline void set_dev_or_file_name(const char* value);
  inline void set_dev_or_file_name(const char* value, size_t size);
  inline ::std::string* mutable_dev_or_file_name();
  inline ::std::string* release_dev_or_file_name();
  
  // optional .ScaleShift px_to_pos_scale = 3;
  inline bool has_px_to_pos_scale() const;
  inline void clear_px_to_pos_scale();
  static const int kPxToPosScaleFieldNumber = 3;
  inline const ::ScaleShift& px_to_pos_scale() const;
  inline ::ScaleShift* mutable_px_to_pos_scale();
  inline ::ScaleShift* release_px_to_pos_scale();
  
  // optional .Affine2D px_to_pos_aff2d = 4;
  inline bool has_px_to_pos_aff2d() const;
  inline void clear_px_to_pos_aff2d();
  static const int kPxToPosAff2DFieldNumber = 4;
  inline const ::Affine2D& px_to_pos_aff2d() const;
  inline ::Affine2D* mutable_px_to_pos_aff2d();
  inline ::Affine2D* release_px_to_pos_aff2d();
  
  // optional int32 led_blur1 = 5;
  inline bool has_led_blur1() const;
  inline void clear_led_blur1();
  static const int kLedBlur1FieldNumber = 5;
  inline ::google::protobuf::int32 led_blur1() const;
  inline void set_led_blur1(::google::protobuf::int32 value);
  
  // optional float led_threshold = 6;
  inline bool has_led_threshold() const;
  inline void clear_led_threshold();
  static const int kLedThresholdFieldNumber = 6;
  inline float led_threshold() const;
  inline void set_led_threshold(float value);
  
  // optional int32 led_blur2 = 7;
  inline bool has_led_blur2() const;
  inline void clear_led_blur2();
  static const int kLedBlur2FieldNumber = 7;
  inline ::google::protobuf::int32 led_blur2() const;
  inline void set_led_blur2(::google::protobuf::int32 value);
  
  // optional int32 body_blur1 = 8;
  inline bool has_body_blur1() const;
  inline void clear_body_blur1();
  static const int kBodyBlur1FieldNumber = 8;
  inline ::google::protobuf::int32 body_blur1() const;
  inline void set_body_blur1(::google::protobuf::int32 value);
  
  // optional int32 body_threshold = 9;
  inline bool has_body_threshold() const;
  inline void clear_body_threshold();
  static const int kBodyThresholdFieldNumber = 9;
  inline ::google::protobuf::int32 body_threshold() const;
  inline void set_body_threshold(::google::protobuf::int32 value);
  
  // optional int32 body_blur2 = 10;
  inline bool has_body_blur2() const;
  inline void clear_body_blur2();
  static const int kBodyBlur2FieldNumber = 10;
  inline ::google::protobuf::int32 body_blur2() const;
  inline void set_body_blur2(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:CameraOpt)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_dev_or_file_name();
  inline void clear_has_dev_or_file_name();
  inline void set_has_px_to_pos_scale();
  inline void clear_has_px_to_pos_scale();
  inline void set_has_px_to_pos_aff2d();
  inline void clear_has_px_to_pos_aff2d();
  inline void set_has_led_blur1();
  inline void clear_has_led_blur1();
  inline void set_has_led_threshold();
  inline void clear_has_led_threshold();
  inline void set_has_led_blur2();
  inline void clear_has_led_blur2();
  inline void set_has_body_blur1();
  inline void clear_has_body_blur1();
  inline void set_has_body_threshold();
  inline void clear_has_body_threshold();
  inline void set_has_body_blur2();
  inline void clear_has_body_blur2();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* dev_or_file_name_;
  ::ScaleShift* px_to_pos_scale_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 led_blur1_;
  ::Affine2D* px_to_pos_aff2d_;
  float led_threshold_;
  ::google::protobuf::int32 led_blur2_;
  ::google::protobuf::int32 body_blur1_;
  ::google::protobuf::int32 body_threshold_;
  ::google::protobuf::int32 body_blur2_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(10 + 31) / 32];
  
  friend void  protobuf_AddDesc_tracker_5fpb_2eproto();
  friend void protobuf_AssignDesc_tracker_5fpb_2eproto();
  friend void protobuf_ShutdownFile_tracker_5fpb_2eproto();
  
  void InitAsDefaultInstance();
  static CameraOpt* default_instance_;
};
// -------------------------------------------------------------------

class CameraGroup : public ::google::protobuf::Message {
 public:
  CameraGroup();
  virtual ~CameraGroup();
  
  CameraGroup(const CameraGroup& from);
  
  inline CameraGroup& operator=(const CameraGroup& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CameraGroup& default_instance();
  
  void Swap(CameraGroup* other);
  
  // implements Message ----------------------------------------------
  
  CameraGroup* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CameraGroup& from);
  void MergeFrom(const CameraGroup& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  typedef CameraGroup_CombineStyle CombineStyle;
  static const CombineStyle NONE = CameraGroup_CombineStyle_NONE;
  static const CombineStyle PANOSTITCH = CameraGroup_CombineStyle_PANOSTITCH;
  static const CombineStyle FULL3D = CameraGroup_CombineStyle_FULL3D;
  static inline bool CombineStyle_IsValid(int value) {
    return CameraGroup_CombineStyle_IsValid(value);
  }
  static const CombineStyle CombineStyle_MIN =
    CameraGroup_CombineStyle_CombineStyle_MIN;
  static const CombineStyle CombineStyle_MAX =
    CameraGroup_CombineStyle_CombineStyle_MAX;
  static const int CombineStyle_ARRAYSIZE =
    CameraGroup_CombineStyle_CombineStyle_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CombineStyle_descriptor() {
    return CameraGroup_CombineStyle_descriptor();
  }
  static inline const ::std::string& CombineStyle_Name(CombineStyle value) {
    return CameraGroup_CombineStyle_Name(value);
  }
  static inline bool CombineStyle_Parse(const ::std::string& name,
      CombineStyle* value) {
    return CameraGroup_CombineStyle_Parse(name, value);
  }
  
  // accessors -------------------------------------------------------
  
  // repeated .CameraOpt cam = 1;
  inline int cam_size() const;
  inline void clear_cam();
  static const int kCamFieldNumber = 1;
  inline const ::CameraOpt& cam(int index) const;
  inline ::CameraOpt* mutable_cam(int index);
  inline ::CameraOpt* add_cam();
  inline const ::google::protobuf::RepeatedPtrField< ::CameraOpt >&
      cam() const;
  inline ::google::protobuf::RepeatedPtrField< ::CameraOpt >*
      mutable_cam();
  
  // optional .CameraGroup.CombineStyle combine = 2;
  inline bool has_combine() const;
  inline void clear_combine();
  static const int kCombineFieldNumber = 2;
  inline ::CameraGroup_CombineStyle combine() const;
  inline void set_combine(::CameraGroup_CombineStyle value);
  
  // @@protoc_insertion_point(class_scope:CameraGroup)
 private:
  inline void set_has_combine();
  inline void clear_has_combine();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::CameraOpt > cam_;
  int combine_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_tracker_5fpb_2eproto();
  friend void protobuf_AssignDesc_tracker_5fpb_2eproto();
  friend void protobuf_ShutdownFile_tracker_5fpb_2eproto();
  
  void InitAsDefaultInstance();
  static CameraGroup* default_instance_;
};
// -------------------------------------------------------------------

class Led : public ::google::protobuf::Message {
 public:
  Led();
  virtual ~Led();
  
  Led(const Led& from);
  
  inline Led& operator=(const Led& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Led& default_instance();
  
  void Swap(Led* other);
  
  // implements Message ----------------------------------------------
  
  Led* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Led& from);
  void MergeFrom(const Led& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional float x_pos = 1;
  inline bool has_x_pos() const;
  inline void clear_x_pos();
  static const int kXPosFieldNumber = 1;
  inline float x_pos() const;
  inline void set_x_pos(float value);
  
  // optional float y_pos = 2;
  inline bool has_y_pos() const;
  inline void clear_y_pos();
  static const int kYPosFieldNumber = 2;
  inline float y_pos() const;
  inline void set_y_pos(float value);
  
  // optional float z_pos = 3;
  inline bool has_z_pos() const;
  inline void clear_z_pos();
  static const int kZPosFieldNumber = 3;
  inline float z_pos() const;
  inline void set_z_pos(float value);
  
  // @@protoc_insertion_point(class_scope:Led)
 private:
  inline void set_has_x_pos();
  inline void clear_has_x_pos();
  inline void set_has_y_pos();
  inline void clear_has_y_pos();
  inline void set_has_z_pos();
  inline void clear_has_z_pos();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  float x_pos_;
  float y_pos_;
  float z_pos_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_tracker_5fpb_2eproto();
  friend void protobuf_AssignDesc_tracker_5fpb_2eproto();
  friend void protobuf_ShutdownFile_tracker_5fpb_2eproto();
  
  void InitAsDefaultInstance();
  static Led* default_instance_;
};
// -------------------------------------------------------------------

class TrackerOpt : public ::google::protobuf::Message {
 public:
  TrackerOpt();
  virtual ~TrackerOpt();
  
  TrackerOpt(const TrackerOpt& from);
  
  inline TrackerOpt& operator=(const TrackerOpt& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const TrackerOpt& default_instance();
  
  void Swap(TrackerOpt* other);
  
  // implements Message ----------------------------------------------
  
  TrackerOpt* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TrackerOpt& from);
  void MergeFrom(const TrackerOpt& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .CameraGroup group = 1;
  inline int group_size() const;
  inline void clear_group();
  static const int kGroupFieldNumber = 1;
  inline const ::CameraGroup& group(int index) const;
  inline ::CameraGroup* mutable_group(int index);
  inline ::CameraGroup* add_group();
  inline const ::google::protobuf::RepeatedPtrField< ::CameraGroup >&
      group() const;
  inline ::google::protobuf::RepeatedPtrField< ::CameraGroup >*
      mutable_group();
  
  // optional int32 max_n_cams = 2;
  inline bool has_max_n_cams() const;
  inline void clear_max_n_cams();
  static const int kMaxNCamsFieldNumber = 2;
  inline ::google::protobuf::int32 max_n_cams() const;
  inline void set_max_n_cams(::google::protobuf::int32 value);
  
  // optional string timer = 3;
  inline bool has_timer() const;
  inline void clear_timer();
  static const int kTimerFieldNumber = 3;
  inline const ::std::string& timer() const;
  inline void set_timer(const ::std::string& value);
  inline void set_timer(const char* value);
  inline void set_timer(const char* value, size_t size);
  inline ::std::string* mutable_timer();
  inline ::std::string* release_timer();
  
  // optional int32 n_led = 4;
  inline bool has_n_led() const;
  inline void clear_n_led();
  static const int kNLedFieldNumber = 4;
  inline ::google::protobuf::int32 n_led() const;
  inline void set_n_led(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:TrackerOpt)
 private:
  inline void set_has_max_n_cams();
  inline void clear_has_max_n_cams();
  inline void set_has_timer();
  inline void clear_has_timer();
  inline void set_has_n_led();
  inline void clear_has_n_led();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::CameraGroup > group_;
  ::std::string* timer_;
  ::google::protobuf::int32 max_n_cams_;
  ::google::protobuf::int32 n_led_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_tracker_5fpb_2eproto();
  friend void protobuf_AssignDesc_tracker_5fpb_2eproto();
  friend void protobuf_ShutdownFile_tracker_5fpb_2eproto();
  
  void InitAsDefaultInstance();
  static TrackerOpt* default_instance_;
};
// ===================================================================


// ===================================================================

// ScaleShift

// optional float x_scale = 1;
inline bool ScaleShift::has_x_scale() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ScaleShift::set_has_x_scale() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ScaleShift::clear_has_x_scale() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ScaleShift::clear_x_scale() {
  x_scale_ = 0;
  clear_has_x_scale();
}
inline float ScaleShift::x_scale() const {
  return x_scale_;
}
inline void ScaleShift::set_x_scale(float value) {
  set_has_x_scale();
  x_scale_ = value;
}

// optional float x_shift = 2;
inline bool ScaleShift::has_x_shift() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ScaleShift::set_has_x_shift() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ScaleShift::clear_has_x_shift() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ScaleShift::clear_x_shift() {
  x_shift_ = 0;
  clear_has_x_shift();
}
inline float ScaleShift::x_shift() const {
  return x_shift_;
}
inline void ScaleShift::set_x_shift(float value) {
  set_has_x_shift();
  x_shift_ = value;
}

// optional float y_scale = 3;
inline bool ScaleShift::has_y_scale() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ScaleShift::set_has_y_scale() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ScaleShift::clear_has_y_scale() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ScaleShift::clear_y_scale() {
  y_scale_ = 0;
  clear_has_y_scale();
}
inline float ScaleShift::y_scale() const {
  return y_scale_;
}
inline void ScaleShift::set_y_scale(float value) {
  set_has_y_scale();
  y_scale_ = value;
}

// optional float y_shift = 4;
inline bool ScaleShift::has_y_shift() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ScaleShift::set_has_y_shift() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ScaleShift::clear_has_y_shift() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ScaleShift::clear_y_shift() {
  y_shift_ = 0;
  clear_has_y_shift();
}
inline float ScaleShift::y_shift() const {
  return y_shift_;
}
inline void ScaleShift::set_y_shift(float value) {
  set_has_y_shift();
  y_shift_ = value;
}

// -------------------------------------------------------------------

// Affine2D

// repeated float coef = 1;
inline int Affine2D::coef_size() const {
  return coef_.size();
}
inline void Affine2D::clear_coef() {
  coef_.Clear();
}
inline float Affine2D::coef(int index) const {
  return coef_.Get(index);
}
inline void Affine2D::set_coef(int index, float value) {
  coef_.Set(index, value);
}
inline void Affine2D::add_coef(float value) {
  coef_.Add(value);
}
inline const ::google::protobuf::RepeatedField< float >&
Affine2D::coef() const {
  return coef_;
}
inline ::google::protobuf::RepeatedField< float >*
Affine2D::mutable_coef() {
  return &coef_;
}

// -------------------------------------------------------------------

// CameraOpt

// optional int32 id = 1;
inline bool CameraOpt::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CameraOpt::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CameraOpt::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CameraOpt::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 CameraOpt::id() const {
  return id_;
}
inline void CameraOpt::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// optional string dev_or_file_name = 2;
inline bool CameraOpt::has_dev_or_file_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CameraOpt::set_has_dev_or_file_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CameraOpt::clear_has_dev_or_file_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CameraOpt::clear_dev_or_file_name() {
  if (dev_or_file_name_ != &::google::protobuf::internal::kEmptyString) {
    dev_or_file_name_->clear();
  }
  clear_has_dev_or_file_name();
}
inline const ::std::string& CameraOpt::dev_or_file_name() const {
  return *dev_or_file_name_;
}
inline void CameraOpt::set_dev_or_file_name(const ::std::string& value) {
  set_has_dev_or_file_name();
  if (dev_or_file_name_ == &::google::protobuf::internal::kEmptyString) {
    dev_or_file_name_ = new ::std::string;
  }
  dev_or_file_name_->assign(value);
}
inline void CameraOpt::set_dev_or_file_name(const char* value) {
  set_has_dev_or_file_name();
  if (dev_or_file_name_ == &::google::protobuf::internal::kEmptyString) {
    dev_or_file_name_ = new ::std::string;
  }
  dev_or_file_name_->assign(value);
}
inline void CameraOpt::set_dev_or_file_name(const char* value, size_t size) {
  set_has_dev_or_file_name();
  if (dev_or_file_name_ == &::google::protobuf::internal::kEmptyString) {
    dev_or_file_name_ = new ::std::string;
  }
  dev_or_file_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CameraOpt::mutable_dev_or_file_name() {
  set_has_dev_or_file_name();
  if (dev_or_file_name_ == &::google::protobuf::internal::kEmptyString) {
    dev_or_file_name_ = new ::std::string;
  }
  return dev_or_file_name_;
}
inline ::std::string* CameraOpt::release_dev_or_file_name() {
  clear_has_dev_or_file_name();
  if (dev_or_file_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = dev_or_file_name_;
    dev_or_file_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional .ScaleShift px_to_pos_scale = 3;
inline bool CameraOpt::has_px_to_pos_scale() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CameraOpt::set_has_px_to_pos_scale() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CameraOpt::clear_has_px_to_pos_scale() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CameraOpt::clear_px_to_pos_scale() {
  if (px_to_pos_scale_ != NULL) px_to_pos_scale_->::ScaleShift::Clear();
  clear_has_px_to_pos_scale();
}
inline const ::ScaleShift& CameraOpt::px_to_pos_scale() const {
  return px_to_pos_scale_ != NULL ? *px_to_pos_scale_ : *default_instance_->px_to_pos_scale_;
}
inline ::ScaleShift* CameraOpt::mutable_px_to_pos_scale() {
  set_has_px_to_pos_scale();
  if (px_to_pos_scale_ == NULL) px_to_pos_scale_ = new ::ScaleShift;
  return px_to_pos_scale_;
}
inline ::ScaleShift* CameraOpt::release_px_to_pos_scale() {
  clear_has_px_to_pos_scale();
  ::ScaleShift* temp = px_to_pos_scale_;
  px_to_pos_scale_ = NULL;
  return temp;
}

// optional .Affine2D px_to_pos_aff2d = 4;
inline bool CameraOpt::has_px_to_pos_aff2d() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CameraOpt::set_has_px_to_pos_aff2d() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CameraOpt::clear_has_px_to_pos_aff2d() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CameraOpt::clear_px_to_pos_aff2d() {
  if (px_to_pos_aff2d_ != NULL) px_to_pos_aff2d_->::Affine2D::Clear();
  clear_has_px_to_pos_aff2d();
}
inline const ::Affine2D& CameraOpt::px_to_pos_aff2d() const {
  return px_to_pos_aff2d_ != NULL ? *px_to_pos_aff2d_ : *default_instance_->px_to_pos_aff2d_;
}
inline ::Affine2D* CameraOpt::mutable_px_to_pos_aff2d() {
  set_has_px_to_pos_aff2d();
  if (px_to_pos_aff2d_ == NULL) px_to_pos_aff2d_ = new ::Affine2D;
  return px_to_pos_aff2d_;
}
inline ::Affine2D* CameraOpt::release_px_to_pos_aff2d() {
  clear_has_px_to_pos_aff2d();
  ::Affine2D* temp = px_to_pos_aff2d_;
  px_to_pos_aff2d_ = NULL;
  return temp;
}

// optional int32 led_blur1 = 5;
inline bool CameraOpt::has_led_blur1() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void CameraOpt::set_has_led_blur1() {
  _has_bits_[0] |= 0x00000010u;
}
inline void CameraOpt::clear_has_led_blur1() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void CameraOpt::clear_led_blur1() {
  led_blur1_ = 0;
  clear_has_led_blur1();
}
inline ::google::protobuf::int32 CameraOpt::led_blur1() const {
  return led_blur1_;
}
inline void CameraOpt::set_led_blur1(::google::protobuf::int32 value) {
  set_has_led_blur1();
  led_blur1_ = value;
}

// optional float led_threshold = 6;
inline bool CameraOpt::has_led_threshold() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CameraOpt::set_has_led_threshold() {
  _has_bits_[0] |= 0x00000020u;
}
inline void CameraOpt::clear_has_led_threshold() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void CameraOpt::clear_led_threshold() {
  led_threshold_ = 0;
  clear_has_led_threshold();
}
inline float CameraOpt::led_threshold() const {
  return led_threshold_;
}
inline void CameraOpt::set_led_threshold(float value) {
  set_has_led_threshold();
  led_threshold_ = value;
}

// optional int32 led_blur2 = 7;
inline bool CameraOpt::has_led_blur2() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void CameraOpt::set_has_led_blur2() {
  _has_bits_[0] |= 0x00000040u;
}
inline void CameraOpt::clear_has_led_blur2() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void CameraOpt::clear_led_blur2() {
  led_blur2_ = 0;
  clear_has_led_blur2();
}
inline ::google::protobuf::int32 CameraOpt::led_blur2() const {
  return led_blur2_;
}
inline void CameraOpt::set_led_blur2(::google::protobuf::int32 value) {
  set_has_led_blur2();
  led_blur2_ = value;
}

// optional int32 body_blur1 = 8;
inline bool CameraOpt::has_body_blur1() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void CameraOpt::set_has_body_blur1() {
  _has_bits_[0] |= 0x00000080u;
}
inline void CameraOpt::clear_has_body_blur1() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void CameraOpt::clear_body_blur1() {
  body_blur1_ = 0;
  clear_has_body_blur1();
}
inline ::google::protobuf::int32 CameraOpt::body_blur1() const {
  return body_blur1_;
}
inline void CameraOpt::set_body_blur1(::google::protobuf::int32 value) {
  set_has_body_blur1();
  body_blur1_ = value;
}

// optional int32 body_threshold = 9;
inline bool CameraOpt::has_body_threshold() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void CameraOpt::set_has_body_threshold() {
  _has_bits_[0] |= 0x00000100u;
}
inline void CameraOpt::clear_has_body_threshold() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void CameraOpt::clear_body_threshold() {
  body_threshold_ = 0;
  clear_has_body_threshold();
}
inline ::google::protobuf::int32 CameraOpt::body_threshold() const {
  return body_threshold_;
}
inline void CameraOpt::set_body_threshold(::google::protobuf::int32 value) {
  set_has_body_threshold();
  body_threshold_ = value;
}

// optional int32 body_blur2 = 10;
inline bool CameraOpt::has_body_blur2() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void CameraOpt::set_has_body_blur2() {
  _has_bits_[0] |= 0x00000200u;
}
inline void CameraOpt::clear_has_body_blur2() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void CameraOpt::clear_body_blur2() {
  body_blur2_ = 0;
  clear_has_body_blur2();
}
inline ::google::protobuf::int32 CameraOpt::body_blur2() const {
  return body_blur2_;
}
inline void CameraOpt::set_body_blur2(::google::protobuf::int32 value) {
  set_has_body_blur2();
  body_blur2_ = value;
}

// -------------------------------------------------------------------

// CameraGroup

// repeated .CameraOpt cam = 1;
inline int CameraGroup::cam_size() const {
  return cam_.size();
}
inline void CameraGroup::clear_cam() {
  cam_.Clear();
}
inline const ::CameraOpt& CameraGroup::cam(int index) const {
  return cam_.Get(index);
}
inline ::CameraOpt* CameraGroup::mutable_cam(int index) {
  return cam_.Mutable(index);
}
inline ::CameraOpt* CameraGroup::add_cam() {
  return cam_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CameraOpt >&
CameraGroup::cam() const {
  return cam_;
}
inline ::google::protobuf::RepeatedPtrField< ::CameraOpt >*
CameraGroup::mutable_cam() {
  return &cam_;
}

// optional .CameraGroup.CombineStyle combine = 2;
inline bool CameraGroup::has_combine() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CameraGroup::set_has_combine() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CameraGroup::clear_has_combine() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CameraGroup::clear_combine() {
  combine_ = 1;
  clear_has_combine();
}
inline ::CameraGroup_CombineStyle CameraGroup::combine() const {
  return static_cast< ::CameraGroup_CombineStyle >(combine_);
}
inline void CameraGroup::set_combine(::CameraGroup_CombineStyle value) {
  GOOGLE_DCHECK(::CameraGroup_CombineStyle_IsValid(value));
  set_has_combine();
  combine_ = value;
}

// -------------------------------------------------------------------

// Led

// optional float x_pos = 1;
inline bool Led::has_x_pos() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Led::set_has_x_pos() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Led::clear_has_x_pos() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Led::clear_x_pos() {
  x_pos_ = 0;
  clear_has_x_pos();
}
inline float Led::x_pos() const {
  return x_pos_;
}
inline void Led::set_x_pos(float value) {
  set_has_x_pos();
  x_pos_ = value;
}

// optional float y_pos = 2;
inline bool Led::has_y_pos() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Led::set_has_y_pos() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Led::clear_has_y_pos() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Led::clear_y_pos() {
  y_pos_ = 0;
  clear_has_y_pos();
}
inline float Led::y_pos() const {
  return y_pos_;
}
inline void Led::set_y_pos(float value) {
  set_has_y_pos();
  y_pos_ = value;
}

// optional float z_pos = 3;
inline bool Led::has_z_pos() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Led::set_has_z_pos() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Led::clear_has_z_pos() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Led::clear_z_pos() {
  z_pos_ = 0;
  clear_has_z_pos();
}
inline float Led::z_pos() const {
  return z_pos_;
}
inline void Led::set_z_pos(float value) {
  set_has_z_pos();
  z_pos_ = value;
}

// -------------------------------------------------------------------

// TrackerOpt

// repeated .CameraGroup group = 1;
inline int TrackerOpt::group_size() const {
  return group_.size();
}
inline void TrackerOpt::clear_group() {
  group_.Clear();
}
inline const ::CameraGroup& TrackerOpt::group(int index) const {
  return group_.Get(index);
}
inline ::CameraGroup* TrackerOpt::mutable_group(int index) {
  return group_.Mutable(index);
}
inline ::CameraGroup* TrackerOpt::add_group() {
  return group_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CameraGroup >&
TrackerOpt::group() const {
  return group_;
}
inline ::google::protobuf::RepeatedPtrField< ::CameraGroup >*
TrackerOpt::mutable_group() {
  return &group_;
}

// optional int32 max_n_cams = 2;
inline bool TrackerOpt::has_max_n_cams() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TrackerOpt::set_has_max_n_cams() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TrackerOpt::clear_has_max_n_cams() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TrackerOpt::clear_max_n_cams() {
  max_n_cams_ = 0;
  clear_has_max_n_cams();
}
inline ::google::protobuf::int32 TrackerOpt::max_n_cams() const {
  return max_n_cams_;
}
inline void TrackerOpt::set_max_n_cams(::google::protobuf::int32 value) {
  set_has_max_n_cams();
  max_n_cams_ = value;
}

// optional string timer = 3;
inline bool TrackerOpt::has_timer() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TrackerOpt::set_has_timer() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TrackerOpt::clear_has_timer() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TrackerOpt::clear_timer() {
  if (timer_ != &::google::protobuf::internal::kEmptyString) {
    timer_->clear();
  }
  clear_has_timer();
}
inline const ::std::string& TrackerOpt::timer() const {
  return *timer_;
}
inline void TrackerOpt::set_timer(const ::std::string& value) {
  set_has_timer();
  if (timer_ == &::google::protobuf::internal::kEmptyString) {
    timer_ = new ::std::string;
  }
  timer_->assign(value);
}
inline void TrackerOpt::set_timer(const char* value) {
  set_has_timer();
  if (timer_ == &::google::protobuf::internal::kEmptyString) {
    timer_ = new ::std::string;
  }
  timer_->assign(value);
}
inline void TrackerOpt::set_timer(const char* value, size_t size) {
  set_has_timer();
  if (timer_ == &::google::protobuf::internal::kEmptyString) {
    timer_ = new ::std::string;
  }
  timer_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* TrackerOpt::mutable_timer() {
  set_has_timer();
  if (timer_ == &::google::protobuf::internal::kEmptyString) {
    timer_ = new ::std::string;
  }
  return timer_;
}
inline ::std::string* TrackerOpt::release_timer() {
  clear_has_timer();
  if (timer_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = timer_;
    timer_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional int32 n_led = 4;
inline bool TrackerOpt::has_n_led() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TrackerOpt::set_has_n_led() {
  _has_bits_[0] |= 0x00000008u;
}
inline void TrackerOpt::clear_has_n_led() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void TrackerOpt::clear_n_led() {
  n_led_ = 0;
  clear_has_n_led();
}
inline ::google::protobuf::int32 TrackerOpt::n_led() const {
  return n_led_;
}
inline void TrackerOpt::set_n_led(::google::protobuf::int32 value) {
  set_has_n_led();
  n_led_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::CameraGroup_CombineStyle>() {
  return ::CameraGroup_CombineStyle_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tracker_5fpb_2eproto__INCLUDED
